import { BoundedFifoMap } from "./bounded-map.js";

/** A short, free-text status message accompanying a SOS (e.g. "gamba rotta, non posso camminare") — distinct from `Drop`'s `text`, which is a public notice, not an emergency signal; optional, same bound as any other short free-text field in this codebase. */
export const MAX_BEACON_MESSAGE_LENGTH = 200;

/**
 * Fixed, exact `ContentMetadata.name` an emergency beacon is published
 * under — mirrors `DROP_CONTENT_NAME` (`drops.ts`): the content itself
 * (different signed bytes -> different `contentId`) already distinguishes
 * one SOS from another, so there is exactly one name here, not a family of
 * them (unlike `chat:<channel>`, which needs per-instance naming).
 * `NomadNode.considerEmergencyBeacon()` recognizes a newly-announced piece
 * of content as an emergency beacon by an exact match against this
 * constant.
 */
export const EMERGENCY_BEACON_CONTENT_NAME = "emergency-beacon";

/**
 * The signed `content://` payload a SOS carries — mirrors `DropPayload`
 * (`drops.ts`): `timestamp` lives here, inside the bytes the publisher's
 * signature actually covers (`contentSigningPayload()`, `content.ts`),
 * never in `ContentMetadata.createdAt`, which isn't part of what gets
 * signed. Unlike `DropPayload`, there is no `kind` field — a SOS has no
 * lower-severity variant, it is always published at `Priority.EMERGENCY`
 * (`NomadNode.sendEmergencyBeacon()`). There is also no `deviceId`/author
 * field: the originator's identity is already `ContentMetadata.publisherId`,
 * authenticated by the content signature — a redundant payload field would
 * only be one more thing to keep consistent with the real one.
 *
 * `lat`/`lon` are deliberately optional and never generated by this module
 * itself: `docs/beacon.md` ("NOMAD Card") is explicit that the Card has no
 * GPS of its own — a position, when present, was attached by whichever
 * caller of `sendEmergencyBeacon()` actually has one (a paired phone, an
 * externally GPS-equipped relay). Same "position of whoever is reporting"
 * pattern already used by `location-registry.ts`/`drops.ts`, just optional
 * here since a pure Beacon Mode device genuinely may not have one to give.
 */
export interface EmergencyBeaconPayload {
  message?: string;
  lat?: number;
  lon?: number;
  timestamp: number;
}

/**
 * Validates and extracts an emergency beacon payload from already-fetched,
 * signature-verified `content://` bytes — same defensive posture as every
 * other network-sourced payload in this codebase (`extractDropPayload()`,
 * `extractChannelMessagePayload()`): never trusted just because the JSON
 * parsed and the outer content signature checked out. `undefined` for
 * anything not shaped exactly like a valid beacon.
 */
export function extractEmergencyBeaconPayload(payload: unknown): EmergencyBeaconPayload | undefined {
  if (!payload || typeof payload !== "object") return undefined;
  const p = payload as Record<string, unknown>;
  let message: string | undefined;
  if (p.message !== undefined) {
    if (typeof p.message !== "string" || p.message.length === 0 || p.message.length > MAX_BEACON_MESSAGE_LENGTH) return undefined;
    message = p.message;
  }
  let lat: number | undefined;
  if (p.lat !== undefined) {
    if (typeof p.lat !== "number" || !Number.isFinite(p.lat) || p.lat < -90 || p.lat > 90) return undefined;
    lat = p.lat;
  }
  let lon: number | undefined;
  if (p.lon !== undefined) {
    if (typeof p.lon !== "number" || !Number.isFinite(p.lon) || p.lon < -180 || p.lon > 180) return undefined;
    lon = p.lon;
  }
  if (typeof p.timestamp !== "number" || !Number.isFinite(p.timestamp)) return undefined;
  return { message, lat, lon, timestamp: p.timestamp };
}

/**
 * A SOS as observed and stored locally by this node — the Emergency Node
 * "sightings" registry (`docs/beacon.md`, "Cosa manca davvero" #3).
 * `beaconContentId` mirrors `Drop.dropId` (the underlying content's
 * `contentId`, a hash of the signed bytes — a natural, tamper-evident id,
 * no separate one generated). `deviceId` is `ContentMetadata.publisherId`
 * — cryptographically authenticated by the content signature, never a
 * payload claim.
 *
 * `receivedFrom` is deliberately **not** a full multi-hop path (which relay
 * relayed this to which other relay, all the way back to origin) — that
 * would require mutating the payload at every hop, incompatible with this
 * codebase's "signed content is immutable" model without redesigning the
 * signature itself (see `emergency-beacon.ts`'s module-level "fuori scope"
 * note in the plan this shipped from). It is only the single hop closest to
 * *this* node: the `fromPeerId` that delivered the `CONTENT_ANNOUNCE`
 * carrying this beacon directly to this node — an honest partial answer
 * (which relay/peer told *me* about this) rather than a fabricated
 * complete one, useful to correlate with `RelayRegistry` (`relay-registry.ts`)
 * when that peer happens to be a registered Fixed/Mobile Relay.
 * `undefined` when this node originated the beacon itself (nothing
 * "received" it) or the deliverer wasn't itself a real peer relationship —
 * see `NomadNode.considerEmergencyBeacon()`'s own doc comment.
 */
export interface EmergencyBeaconSighting {
  beaconContentId: string;
  deviceId: string;
  message?: string;
  lat?: number;
  lon?: number;
  timestamp: number;
  /** When this node itself first recorded the sighting (`Date.now()`, local clock) — distinct from `timestamp`, which is the originator's own claimed time. */
  observedAt: number;
  receivedFrom?: string;
}

export interface EmergencyBeaconsOptions {
  /** Max distinct sightings tracked at once (spec §57 resource limits). */
  maxBeacons?: number;
}

const DEFAULT_MAX_BEACONS = 512;

/**
 * Local, best-effort view of emergency beacon sightings this node has
 * learned about — built entirely from already-verified `content://`
 * publications named exactly `EMERGENCY_BEACON_CONTENT_NAME`, the same
 * architectural placement as `Drops`/`PublicChannels`: pure mesh-internal
 * state derived from already-signed content, never itself a separately-
 * signed/propagated structure. `NomadNode.sendEmergencyBeacon()`/
 * `considerEmergencyBeacon()` are the only callers.
 *
 * **No lazy expiry, unlike `Drops`/`LocationRegistry`**: an Emergency Node
 * operator needs to be able to see a SOS *after* the situation is (one
 * hopes) resolved — for follow-up, record-keeping, or simply because
 * nobody has told this node otherwise. `ContentMetadata.expiresAt` (set by
 * `sendEmergencyBeacon()`'s `ttlMs`) still governs how long the *content*
 * itself stays fetchable from the mesh, but the local sighting record
 * survives that independently, same reasoning `RelayRegistry` already used
 * for not expiring a physical installation on a timer.
 *
 * **No `trustRank`/eviction pesata sulla fiducia**: unlike `Drops`, a
 * throwaway/never-seen-before identity is not just tolerated here, it is
 * the *expected* case (`docs/beacon.md` #4, "Card usa-e-getta") — ranking
 * by trust would systematically favor evicting exactly the sightings an
 * Emergency Node most needs to keep. Plain FIFO under `maxBeacons` is the
 * only fair policy; the real anti-flood defense for this feature lives
 * upstream, at the transport layer (`SimulatedLinkTransport.receiveBroadcast()`)
 * and at the per-caller origination budget (`NomadNode.sendEmergencyBeacon()`),
 * not in eviction policy here.
 */
export class EmergencyBeacons {
  private readonly sightings: BoundedFifoMap<string, EmergencyBeaconSighting>;

  constructor(options: EmergencyBeaconsOptions = {}) {
    this.sightings = new BoundedFifoMap({ maxSize: options.maxBeacons ?? DEFAULT_MAX_BEACONS });
  }

  /** No-op (not an error) if `sighting.beaconContentId` is already known — a re-announce/retransmit of the same SOS never overwrites the original sighting record (in particular, never loses the original `receivedFrom`/`observedAt`). */
  record(sighting: EmergencyBeaconSighting): void {
    if (this.sightings.has(sighting.beaconContentId)) return;
    this.sightings.set(sighting.beaconContentId, sighting);
  }

  /** Every currently-known sighting, newest first. */
  list(): EmergencyBeaconSighting[] {
    return [...this.sightings.values()].sort((a, b) => b.observedAt - a.observedAt);
  }
}
