import type { NomadNode } from "../../node/src/node.js";

/**
 * Registers `service://ai` — spec §37's own worked example: a weak device
 * asks the mesh for an answer generated by a local AI, and the mesh finds a
 * more capable node able to provide it. That "find a capable node" part is
 * entirely `discoverService()`/`callService()` (spec §35-36, `node.ts`) —
 * nothing here is specific to AI beyond *which* HTTP backend the handler
 * proxies to, exactly like `KiwixGateway.registerSearchService()` proxies
 * to Kiwix. A weak node three hops away calls `service://ai` the same way
 * it would call `service://kiwix-search`, never learning which node
 * actually answered.
 *
 * Kept as its own small class rather than a method on `KiwixGateway`: this
 * is a different NOMAD sub-service (Ollama, not Kiwix — `docs/reuse-vs-new.md`
 * lists both as separate containerized services), reachable at its own
 * `baseUrl` with its own independent failure mode. A production Project
 * NOMAD deployment may well run Kiwix and Ollama on different ports or
 * hosts even though both are "the same NOMAD instance" conceptually — a
 * gateway node is free to construct one, both, or neither of these classes
 * depending on which NOMAD sub-services it actually wants to expose.
 */
export class AiGateway {
  constructor(
    private readonly node: NomadNode,
    /** Base URL of the NOMAD/Ollama HTTP API, e.g. `http://127.0.0.1:PORT` (a `FakeOllamaServer` in tests/demo, a real Ollama instance behind Project NOMAD in production). */
    private readonly baseUrl: string,
  ) {}

  /**
   * Registers `service://ai`. Never caches — every call is a genuine live
   * request to the AI backend, same "no snapshot" posture as
   * `KiwixGateway.registerSearchService()`: a cached answer would be a
   * plausible-looking stale response, worse than a slow real one.
   *
   * `resourceRequirements` is spec §35's free-text field, descriptive only
   * here — this prototype's `discoverService()`/`callService()` has no
   * capability-based ranking among multiple providers of the same service
   * (it calls whichever one it learns about first), so setting it doesn't
   * change which node ends up serving a given call. It's set anyway so a
   * human reading a `ServiceAnnouncement` (e.g. via the web UI, spec §59)
   * sees *why* this service is a plausible candidate for a relay-only role
   * rather than a battery-constrained handheld.
   */
  registerAiService(): void {
    this.node.registerService(
      "service://ai",
      "1.0.0",
      ["chat"],
      async (payload) => {
        const { prompt } = payload as { prompt?: unknown };
        if (typeof prompt !== "string" || prompt.length === 0) {
          throw new Error("service://ai requires a non-empty string 'prompt' field");
        }

        const res = await fetch(`${this.baseUrl}/api/generate`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt }),
        });
        if (!res.ok) throw new Error(`NOMAD AI backend failed (HTTP ${res.status})`);
        const body = (await res.json()) as { response?: unknown };
        if (typeof body.response !== "string") {
          throw new Error("NOMAD AI backend returned a malformed response");
        }
        return { response: body.response };
      },
      { resourceRequirements: "modello linguistico locale — nodo con risorse adeguate, tipicamente non a batteria" },
    );
  }
}
