import type { IncomingMessage, ServerResponse } from "node:http";
import { LoopbackHttpServer, sendJson } from "../../node/src/loopback-http-server.js";

export interface FakeOllamaServerOptions {
  /** Port to listen on; 0 (default) lets the OS assign one, same convention as FakeNomadServer/TcpTransport. */
  port?: number;
  host?: string;
  /** Simulated per-request delay in ms, so tests can exercise AiGateway's async plumbing under something other than instant loopback response. */
  latencyMs?: number;
}

const MAX_BODY_BYTES = 1_000_000;

/** Distinguishes "the body was too big" from every other stream failure (client disconnect, socket reset) — `route()` needs to tell them apart to answer with the right status code instead of always claiming 413. */
class BodyTooLargeError extends Error {}

/** Reads and concatenates a request body, rejecting with `BodyTooLargeError` once it exceeds `maxBytes` instead of buffering an unbounded amount from a hostile or broken client — any other stream failure rejects with the original error unchanged. */
function readBody(req: IncomingMessage, maxBytes: number): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let total = 0;
    let settled = false;
    req.on("data", (chunk: Buffer) => {
      if (settled) return;
      total += chunk.length;
      if (total > maxBytes) {
        settled = true;
        req.destroy();
        reject(new BodyTooLargeError("request body too large"));
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (!settled) resolve(Buffer.concat(chunks));
    });
    req.on("error", (err) => {
      if (!settled) {
        settled = true;
        reject(err);
      }
    });
  });
}

/**
 * Stands in for the Ollama service a real Project NOMAD instance would
 * otherwise containerize (`docs/reuse-vs-new.md`: "Ollama (LLM locale) —
 * esiste, containerizzato — consumato tramite gateway", spec §37's own
 * worked example: a weak device asks the mesh for an answer generated by a
 * local AI, and the mesh finds a more capable node able to provide it).
 * Deliberately not a language model of any kind — a small, deterministic,
 * keyword-matched canned-response table (`addAnswer()`), just enough to
 * prove `AiGateway`'s round trip end-to-end without an actual model
 * download in a test/demo process. Mirrors `FakeNomadServer`'s role and
 * shape exactly, but for a different NOMAD sub-service reachable at its
 * own URL — see `AiGateway`'s doc comment for why they're kept separate
 * rather than merged into one class.
 */
export class FakeOllamaServer {
  private readonly answers = new Map<string, string>();
  private defaultAnswer = "Non ho una risposta per questo.";
  private readonly latencyMs: number;
  private readonly httpServer: LoopbackHttpServer;

  constructor(options: FakeOllamaServerOptions = {}) {
    this.latencyMs = options.latencyMs ?? 0;
    this.httpServer = new LoopbackHttpServer((req, res) => this.handleRequest(req, res), {
      port: options.port,
      host: options.host,
    });
  }

  get port(): number {
    return this.httpServer.port;
  }

  /** Registers a canned response returned whenever a prompt contains `keyword` (case-insensitive substring match — the point is to demonstrate the gateway round trip, not to model real language understanding). Later calls take precedence only if `keyword` repeats; otherwise the first matching keyword in registration order wins. */
  addAnswer(keyword: string, answer: string): void {
    this.answers.set(keyword.toLowerCase(), answer);
  }

  /** Response returned when no registered keyword matches the prompt — defaults to a generic "I don't know" rather than an empty string, so a test/demo never mistakes silence for a real answer. */
  setDefaultAnswer(answer: string): void {
    this.defaultAnswer = answer;
  }

  async start(): Promise<void> {
    await this.httpServer.start();
  }

  async stop(): Promise<void> {
    await this.httpServer.stop();
  }

  private handleRequest(req: IncomingMessage, res: ServerResponse): void {
    const respond = (): void => void this.route(req, res);
    if (this.latencyMs > 0) setTimeout(respond, this.latencyMs);
    else respond();
  }

  private async route(req: IncomingMessage, res: ServerResponse): Promise<void> {
    const url = new URL(req.url ?? "/", "http://localhost");
    if (req.method !== "POST" || url.pathname !== "/api/generate") {
      sendJson(res, 404, { error: "not found" });
      return;
    }

    let raw: Buffer;
    try {
      raw = await readBody(req, MAX_BODY_BYTES);
    } catch (err) {
      if (res.writableEnded || res.destroyed) return; // connection already gone — nothing to answer
      if (err instanceof BodyTooLargeError) {
        sendJson(res, 413, { error: "request body too large" });
      } else {
        // Some other stream failure (client disconnect, socket reset) — distinct from the body
        // genuinely being too large, so it gets its own status instead of a misleading 413.
        sendJson(res, 400, { error: "failed to read request body" });
      }
      return;
    }

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw.toString("utf8"));
    } catch {
      // Malformed JSON body — same defensive posture as FakeNomadServer's decodeURIComponent
      // guard (docs/security.md bug #19): an uncaught throw inside a request listener takes down
      // the whole process, not just this one request.
      sendJson(res, 400, { error: "malformed JSON body" });
      return;
    }

    const prompt = (parsed as { prompt?: unknown } | null)?.prompt;
    if (typeof prompt !== "string") {
      sendJson(res, 400, { error: "'prompt' must be a string" });
      return;
    }

    const needle = prompt.toLowerCase();
    let response = this.defaultAnswer;
    for (const [keyword, answer] of this.answers) {
      if (needle.includes(keyword)) {
        response = answer;
        break;
      }
    }
    sendJson(res, 200, { response });
  }
}
